language: node_js
after_success:
  - $(npm bin)/set-up-ssh --key "${encrypted_af3e1377dcfa_key}"
      --iv "${encrypted_af3e1377dcfa_iv}"
      --path-encrypted-key github_deploy_key.enc
  # - $(npm bin)/update-branch --commands 'npm run build'
  #     --commit-message "Update gh-pages @ ${TRAVIS_COMMIT}"
  #     --directory 'dist'
  #     --distribution-branch 'gh-pages'
  #     --source-branch 'master'
git:
  depth: 1
branches:
  only:
    - master